Skip to content
DEV Community
Search...
Powered by  Algolia
Log in
Create account

0
Jump to Comments

9
Save

Boost

Cover image for Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
Henrique Lopes
Henrique Lopes
Posted on 4 de jan. de 2022


74

3
Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github 🐍
#
github
Primeiramente devo deixar claro que esse artigo foi desenvolvido com base em vários outros artigos e reconstruído para deixar o mais claro possível a forma para inserir o Snake Game em seu perfil.

Funcionamento. "Contributions in the last year":
Basicamente o Snake game funciona realizando uma coleta da sua tabela de contribuições no Github. ele faz a renderização dessas informações e gera dois arquivos, um em formato gif e outro em svg. São esses arquivos que iremos utilizar para inserir a animação no perfil do Github.

Repositorio do projeto a ser utilizado: Platane/snk

Exemple

Requisito. "Repositório base":
Para que você possa prosseguir é necessário que você tenha o repositório do perfil (repositório com o mesmo nome de usuário), porém para gerar os arquivos também funciona em outro repositório.

Actions. "Configuração inicial":
Inicialmente é necessário que você acesse o seu repositório escolhido e vá em Settings.

Configuração inicial

No menu vertical ao lado esquerdo selecione o menu Actions e em seguida ative a permissão “Allow all actions”. Também é possível selecionar diretamente o repositório.

Ative a permissão

Actions. "Criando Gerador":
Agora que temos o repositório configurado iremos adicionar o "script" para gerar dos arquivos. No repositório, vá em Actions.

Criando o gerador

Em seguida vamos utilizar “Simple workflow” apenas com o mínimo necessário para rodar o codigo.

Configurando

Agora é apenas alterar o nome do arquivo e colar o código da configuração com o seu usuário.

Alterar jnome do arquivo

alterando o username



# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: VitorGirottto #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


Retornando na opção Actions do repositório, clique em “Run workflow”:

Repositorio

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione a branch output:
output

E aqui estão os arquivos gerados que você pode utilizar como bem entender:

Arquivos

Codigo Github para utilização:

![snake gif](https://github.com/VitorGirottto/Readme/blob/output/github-contribution-grid-snake.svg)

profile
DevCycleHQ
Promoted

DevCycle image

Fast, Flexible Releases with OpenFeature Built-in
Ship faster on the first feature management platform with OpenFeature built-in to all of our open source SDKs.

Start shipping

Read More
Top comments (0)
Subscribe
pic
Add to the discussion
Code of Conduct • Report abuse
profile
Stellar Development Foundation
Promoted

Dev Diairies image

User Feedback & The Pivot That Saved The Project
🔥 Check out Episode 3 of Dev Diairies, following a successful Hackathon project turned startup.

Watch full video 🎥


Henrique Lopes
Follow
"Não há razão alguma em usar a palavra “impossível” para descrever algo que claramente pode acontecer."
Joined
5 de set. de 2021
Trending on DEV Community 
Cesar Aguirre profile image
The First Time I Saw a Computer—A Bit of Nostalgia
#discuss #watercooler #jokes #programming
Hadil Ben Abdallah profile image
💻 How to Crack Any Software Developer Interview in 2025 🔥
#programming #softwaredevelopment #career #interview
Ingo Steinke, web developer profile image
8 Alternatives to AI for Coding and Creativity
#webdev #programming #productivity #ai
profile
AWS
Promoted

AWS Q Developer image

Build your favorite retro game with Amazon Q Developer CLI in the Challenge & win a T-shirt!
Feeling nostalgic? Build Games Challenge is your chance to recreate your favorite retro arcade style game using Amazon Q Developer’s agentic coding experience in the command line interface, Q Developer CLI.

Participate Now



# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


💎 DEV Diamond Sponsors

Thank you to our Diamond Sponsors for supporting the DEV Community

Google AI - Official AI Model and Platform Partner
Google AI is the official AI Model and Platform Partner of DEV

Neon - Official Database Partner
Neon is the official database partner of DEV

Algolia - Official Search Partner
Algolia is the official search partner of DEV

DEV Community — A space to discuss and keep up software development and manage your software career

Home
Tags
DEV Education Tracks
About
Contact
Code of Conduct
Privacy Policy
Terms of use
Built on Forem — the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community © 2016 - 2025.
